# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

comment: false

ignore:
  - "**/__init__.py"
  - "maraboupy/__main__.py"
  - "maraboupy/test"
  - "maraboupy/test_requirements.txt"

coverage:
  status:
    # Make sure the total coverage decreased by at most 1%
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        paths:
          - "maraboupy"
    # Make sure the new added code is at least 80% covered
    patch:
      default:
        target: 80%
        base: auto
        paths:
          - "maraboupy"



