# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

comment: false

ignore:
  - "**/__init__.py"
  - "maraboupy/test"

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
        paths:
          - "src"
          - "maraboupy"
   

