ROOT_DIR = ..

SUBDIRS += \
	tests\

LOCAL_INCLUDES += \

LINK_FLAGS += \

LOCAL_LIBRARIES += \

include $(ROOT_DIR)/Rules.mk

#
# Local Variables:
# compile-command: "make -C .. "
# tags-file-name: "../TAGS"
# c-basic-offset: 4
# End:
#
