ROOT_DIR = ../..

SUBDIRS += \
	acas_example \
	berkeley_example \

include $(ROOT_DIR)/Rules.mk

#
# Local Variables:
# compile-command: "make -C ../.. "
# tags-file-name: "../../TAGS"
# c-basic-offset: 4
# End:
#
