ROOT_DIR = ..

SUBDIRS += \
	common \
	engine \
	input_parsers \

include $(ROOT_DIR)/Rules.mk

#
# Local Variables:
# compile-command: "make -C .. "
# tags-file-name: "../TAGS"
# c-basic-offset: 4
# End:
#
